[package]
name = "shirtshirts"
version = "0.1.0"
authors = ["Richard Wang <zhwang@live.com.au>"]

[dependencies.trousers]
git = "https://github.com/rzhw/rust-trousers.git"

[dependencies.newt]
git = "https://github.com/rzhw/rust-newt.git"
